# Generated by Django 4.2.1 on 2023-05-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_cart_products_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='imageurl',
            field=models.URLField(null=True),
        ),
    ]
