# Generated by Django 4.2.1 on 2023-05-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_user_imageurl_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='products',
            field=models.ManyToManyField(to='myapp.product'),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
