# Generated by Django 4.2.1 on 2023-05-20 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_orderitem_product_orderitem_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='products',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.product'),
        ),
    ]
